services:
  tender_ui:
    container_name: tender_ui_test
    build:
      context: .  # Project repo folder
      dockerfile: ./dockerjenkins/Dockerfile

    image: datastackdevops/tender_ui:0.0.81

    ports:
      - 7023:3000
    volumes:
      - ./logs:/app\logs:rw
